# -*- coding: utf-8 -*-
"""LightFM Mac Train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yID3OwJjMOQDQgAz3GRo51Ctxq_rSXjr

[Cell 1] 구글 드라이브 마운트


코랩에 드라이브를 연결하여 CSV 파일을 읽어올 수 있게 합니다.
"""

from google.colab import drive
drive.mount('/content/drive')

"""[Cell 2] 저장소 클론 및 Colab 전용 무결점 훈련 환경 세팅


로컬 Mac에서는 Miniforge를 썼다면, 코랩(Ubuntu)에서는 컴파일러 세팅 후 lightfm-next로 빌드 지옥을 완벽히 우회합니다.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # 1. 기존 폴더 청소 및 최신 코드 다운로드
# # (아래 git clone 명령어는 중간에 엔터 없이 "한 줄"로 완전히 이어진 단일 명령어입니다)
# rm -rf /content/book-curation
# git clone --depth 1 --branch dev --single-branch https://oauth2:glpat-zAcg6rA2Qh6HdoPRvXe0vmM6MQpvOjEKdTptY29pcA8.01.171q1jmby@gitlab.com/book-curation/book-curation.git /content/book-curation
# 
# # 2. 우분투 및 파이썬 의존성 설치 (이미 이전 실행 때 다 깔려있어서 1초 만에 완료됩니다!)
# sudo apt-get update -y
# sudo apt-get install -y build-essential gcc g++ python3-dev
# pip install --upgrade pip setuptools wheel
# pip install cython numpy scipy joblib
# pip install lightfm-next
# 
# # 3. 설치 정상 완료 점검
# ls /content/book-curation/apps/ai-server/script/train_lightfm.py
#

"""[Cell 3] 3 Epoch 테스트 훈련

공유해주신 가이드라인과 똑같이, 먼저 3 에폭만 돌려서 로그가 잘 찍히는지 점검합니다. 결과물 아티팩트(weights.joblib 포함)는 구글 드라이브로 직접 저장되도록 경로를 지정합니다.
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/book-curation/apps/ai-server

!python script/flatten_persona_events.py \
  --input-file "/content/drive/MyDrive/AI Book Curation/Persona Data/persona_full_result_000_099.json" \
  --output-file "/content/drive/MyDrive/AI Book Curation/Persona Data/persona_events.jsonl"

"""[Cell 4] 30 Epoch 본 학습 (최종 가중치 획득)

3 Epoch 테스트가 무사히 돌아가면, 본격적으로 30 Epoch 학습을 진행하여 서빙에 쓸 최종 가중치를 얻어냅니다.
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/book-curation/apps/ai-server

!python script/train_lightfm.py \
  --events-path "/content/drive/MyDrive/AI Book Curation/Persona Data/persona_events.jsonl" \
  --output-dir "/content/drive/MyDrive/AI Book Curation/lightfm_latest_artifact" \
  --epochs 30 \
  --loss warp

"""[Cell 5] (선택) BPR Loss 모델 비교


WARP 대신 BPR 방식으로도 학습하여 결과를 비교하고 싶다면 아래 셀을 실행합니다.
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/book-curation/apps/ai-server

!python script/train_lightfm.py \
  --events-path "/content/drive/MyDrive/AI Book Curation/Persona Data/persona_events.jsonl" \
  --output-dir "/content/drive/MyDrive/AI Book Curation/lightfm-artifacts/bpr_latest_colab" \
  --epochs 30 \
  --loss bpr