# -*- coding: utf-8 -*-
"""NvidiaTrain

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXxBLyJI_Vyd_AawW4fILJk-9PjHZ7DT

Cell 1: 환경 설치 및 설정
"""

# !pip install -q huggingface_hub numpy tqdm

import os
import sys
import json
import numpy as np
from pathlib import Path
from typing import List, Dict, Any, Optional

# `.env.local` 파일 로드 및 경로 설정
# ai-server 폴더를 sys.path에 추가하여 app 패키지를 찾을 수 있게 함
PROJECT_ROOT = Path(__file__).parent.absolute()
AI_SERVER_PATH = PROJECT_ROOT / "book-curation" / "apps" / "ai-server"
if str(AI_SERVER_PATH) not in sys.path:
    sys.path.append(str(AI_SERVER_PATH))

# pydantic/settings를 위해 .env.local을 환경 변수에 직접 로드
dotenv_path = AI_SERVER_PATH / ".env.local"
if dotenv_path.exists():
    with open(dotenv_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            # 빈 줄이나 주석 건너뛰기, 따옴표 제거
            if line and not line.startswith('#') and '=' in line:
                key, value = line.split('=', 1)
                value = value.strip().strip('"').strip("'")
                os.environ[key] = value

# 로컬 서버 라이브러리 임포트
try:
    from app.core.config import settings
    # settings가 로드된 후에도 명시적으로 필요한 변수 체크
    if not os.environ.get("CLOVA_API_KEY") and hasattr(settings, "CLOVA_API_KEY"):
        os.environ["CLOVA_API_KEY"] = settings.CLOVA_API_KEY
    
    from app.services.retrieval.qdrant_search import BookQdrantSearcher
    HAS_QDRANT = True
    print(f"성공: Qdrant 설정을 로드했습니다. (Endpoint: {settings.QDRANT_URL})")
except Exception as e:
    HAS_QDRANT = False
    print(f"경고: Qdrant 설정을 로드하지 못했습니다: {e}")
    print("로컬 JSON 모드로 전환을 시도합니다.")

# drive.mount('/content/drive')  # 로컬 환경이므로 비활성화

# HF_TOKEN = userdata.get('HF_TOKEN') # 로컬 config 사용 예정

BASE_PATH   = './' # 로컬 경로로 수정
OUTPUT_PATH = './synthetic_persona_output'
CACHE_PATH  = './synthetic_persona_output/embedding_cache'

Path(OUTPUT_PATH).mkdir(parents=True, exist_ok=True)
Path(CACHE_PATH).mkdir(parents=True, exist_ok=True)

print('환경 설정 완료')
print(f'BASE_PATH   : {BASE_PATH}')
print(f'OUTPUT_PATH : {OUTPUT_PATH}')
print(f'CACHE_PATH  : {CACHE_PATH}')

"""Cell 2: 데이터 로드"""

PERSONAS_PATH = './persona_tracks.json' # 트랙 데이터가 포함된 새 파일로 변경
BOOKS_PATH    = './books_sample_100000.json'

if not Path(PERSONAS_PATH).exists():
    print(f"경고: {PERSONAS_PATH} 파일이 없습니다. 대체 파일을 찾습니다...")
    PERSONAS_PATH = './persona_full_result_000_099 (2).json'

with open(PERSONAS_PATH, 'r', encoding='utf-8') as f:
    personas = json.load(f)

# 페르소나 데이터 구조 정규화 (UUID 추출 등)
for p in personas:
    if 'persona_id' in p and 'uuid' not in p:
        p['uuid'] = p['persona_id']

raw_books = []
if not HAS_QDRANT:
    if Path(BOOKS_PATH).exists():
        with open(BOOKS_PATH, 'r', encoding='utf-8') as f:
            raw_books = json.load(f)
    else:
        print(f"경고: {BOOKS_PATH} 파일이 없습니다. Qdrant가 설정되지 않았으므로 도서 데이터가 필요합니다.")
        # 필요시 빈 리스트로 진행하거나 종료
else:
    print("Qdrant 사용 중: 로컬 books_sample_100000.json 로드를 건너뜁니다.")

# 리스트 또는 dict 래핑 처리
if isinstance(raw_books, dict):
    for key in ['books', 'items', 'data']:
        if key in raw_books:
            raw_books = raw_books[key]
            break

# ISBN 없는 도서 제거 (hallucination 방지)
books = [b for b in raw_books if b.get('isbn')] if not HAS_QDRANT else []

if not HAS_QDRANT:
    print(f'페르소나 수         : {len(personas)}')
    print(f'도서 수 (원본)      : {len(raw_books)}')
    print(f'도서 수 (ISBN 있음) : {len(books)}')
    print()
    if books:
        print('도서 샘플 키:', list(books[0].keys())[:10])
else:
    print(f'페르소나 수         : {len(personas)}')
    print('Qdrant 모드 활성화: 로컬 JSON 도서 데이터를 로드하지 않고 Qdrant API를 사용합니다.')

"""Cell 3: 도서 문서 텍스트 생성"""

def join_list(value):
    if isinstance(value, list):
        return ', '.join(str(x) for x in value if x is not None)
    if value is None:
        return ''
    return str(value)

def get_best_intro(book, max_len=1200):
    for key in ['book_intro', 'simple_intro', 'description', 'pub_review', 'book_index']:
        v = book.get(key)
        if v:
            text = str(v).strip()
            if text:
                return text[:max_len]
    return ''

def make_document_text(book, max_intro=1200):
    title       = (book.get('title') or '').strip()
    author      = (book.get('author') or '').strip()
    publisher   = (book.get('publisher') or '').strip()
    pub_date    = (book.get('publish_date') or '').strip()
    categories  = book.get('categories') or book.get('cate_depth1') or []
    cate_depth1 = book.get('cate_depth1') or []
    kcid        = book.get('kcid') or []

    cate_text = join_list(categories) or join_list(cate_depth1)
    kcid_text = join_list(kcid)
    intro     = get_best_intro(book, max_intro)
    book_idx  = str(book.get('book_index') or '').strip()[:max_intro]
    pub_rev   = str(book.get('pub_review') or '').strip()[:max_intro]
    auth_intr = str(book.get('author_intro') or '').strip()[:max_intro]

    lines = [
        f'제목: {title}',
        f'저자: {author}',
        f'출판사: {publisher}',
        f'출간일: {pub_date}',
        f'카테고리: {cate_text}',
        f'KCID: {kcid_text}',
    ]
    if intro:     lines.append(f'소개: {intro}')
    if book_idx:  lines.append(f'목차: {book_idx}')
    if pub_rev:   lines.append(f'출판사 리뷰: {pub_rev}')
    if auth_intr: lines.append(f'저자 소개: {auth_intr}')

    return '\n'.join(l for l in lines if l and not l.endswith(': ')).strip()

def make_search_text(book):
    title = (book.get('title') or '').strip()
    cate  = join_list(book.get('cate_depth1') or [])
    intro = get_best_intro(book, max_len=300)
    return f'{title} {cate} {intro}'

import ast

# ── 어린이 필터 & 장르 캡 유틸 ──────────────────────────────
def parse_all_cates(book: dict) -> list:
    raw = book.get("cate_depth1") or ""
    if isinstance(raw, list):
        return [c.strip() for c in raw if c]
    try:
        parsed = ast.literal_eval(raw)
        if isinstance(parsed, list):
            return [c.strip() for c in parsed if c]
    except Exception:
        pass
    return [c.strip() for c in raw.split(',') if c.strip()]

def parse_cate_depth1(book: dict) -> str:
    cates = parse_all_cates(book)
    return cates[0] if cates else "기타"

def is_travel_book(book: dict) -> bool:
    return any("여행" in c for c in parse_all_cates(book))

def apply_genre_cap(books: list, max_per_genre: int = 4) -> list:
    CHILD_KEYWORDS = {"어린이", "유아", "초등", "청소년"}
    travel_count = 0
    genre_count = {}
    result = []
    for book in books:
        if any(any(kw in c for kw in CHILD_KEYWORDS) for c in parse_all_cates(book)):
            continue  # 어린이/유아/초등/청소년 책 완전 제거
        if is_travel_book(book):
            if travel_count < max_per_genre:
                result.append(book)
                travel_count += 1
            continue
        key = parse_cate_depth1(book)
        if key == "기타" or genre_count.get(key, 0) < max_per_genre:
            result.append(book)
            genre_count[key] = genre_count.get(key, 0) + 1
    return result

# 검증
if not HAS_QDRANT:
    if books:
        sample = make_document_text(books[0])
        print('=== 도서 문서 텍스트 샘플 ===')
        print(sample[:500])
    else:
        print("경고: 검증할 도서 데이터가 없습니다.")
else:
    print("Qdrant 모드: 개별 도서 문서 텍스트 생성 검증을 건너뜁니다 (검색 시 자동 처리).")

"""Cell 4: 키워드 추출 및 프리필터"""

import re

def extract_keywords(persona):
    """
    persona_full_result JSON 구조에서 검색용 핵심 단어 추출
    """
    keywords = set()

    def tokenize(text):
        if not text: return []
        tokens = re.split(r'[\s,./·및]+', str(text))
        return [t.strip() for t in tokens if len(t.strip()) >= 2]

    # 페르소나 데이터 구조에 따라 필드 선택 필요
    # 기존 track_a/b/c 외에 book_history 같은 필드가 있다면 활용
    if 'track_a' in persona:
        for item in persona.get('track_a', []):
            keywords.update(tokenize(item))
    
    # 텍스트 형태의 특징이 있다면 추가
    for field in ['track_b', 'track_c']:
        if field in persona:
            for item in persona.get(field, []):
                content = item.split(':', 1)[-1] if ':' in item else item
                keywords.update(tokenize(content))

    stop_words = {
        '및', '기반', '통한', '활용', '이용', '관련', '위한',
        '통해', '에서', '으로', '하기', '하는', '있는', '없는',
        '미분류', '꾸준한', '체계적', '규칙적', '꾸준히',
    }
    keywords = {k for k in keywords if k not in stop_words and len(k) >= 2}
    return keywords


def prefilter_books(books, keywords, max_candidates=3000):
    """title + cate_depth1 + simple_intro에서 키워드 매칭 점수 상위 반환"""
    scored = []
    for book in books:
        search_text = make_search_text(book)
        score = sum(1 for kw in keywords if kw in search_text)
        if score > 0:
            scored.append((score, book))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [b for _, b in scored[:max_candidates]]


def build_global_candidate_pool(personas, books, max_candidates_per_persona=3000):
    """전체 100명 페르소나의 후보 도서 유니온 생성 (ISBN 기준 중복 제거)"""
    from tqdm import tqdm
    pool = {}  # isbn -> book
    for p in tqdm(personas, desc='후보 풀 구축'):
        kws = extract_keywords(p)
        candidates = prefilter_books(books, kws, max_candidates=max_candidates_per_persona)
        for b in candidates:
            isbn = str(b.get('isbn'))
            if isbn not in pool:
                pool[isbn] = b
    return list(pool.values())

# 검증: 사용자1
if not HAS_QDRANT:
    sample_kws = extract_keywords(personas[0])
    print(f'사용자1 키워드 수: {len(sample_kws)}')
    print(sorted(sample_kws)[:20])

    sample_candidates = prefilter_books(books, sample_kws)
    print(f'\n사용자1 후보 도서 수: {len(sample_candidates)}')
    print('상위 5권:')
    for b in sample_candidates[:5]:
        print(f'  - {b.get("title")} | {join_list(b.get("cate_depth1", []))}')
else:
    print("Qdrant 모드: 키워드 프리필터링 검증을 건너뜁니다.")

"""Cell 5: KURE 임베딩 함수"""

import time
from huggingface_hub import InferenceClient

# KURE 임베딩 함수용 토큰 (Qdrant 미사용 시 필요)
HF_TOKEN = os.environ.get("HF_TOKEN", "")

client = InferenceClient(
    provider='auto',
    api_key=HF_TOKEN,
)

KURE_MODEL = 'nlpai-lab/KURE-v1'

def embed_text(text, max_retries=5, base_delay=2.0):
    """단일 텍스트 임베딩. 실패 시 exponential backoff 재시도."""
    text = ' '.join(text.strip().split())
    if not text:
        return None

    delay = base_delay
    for attempt in range(1, max_retries + 1):
        try:
            result = client.feature_extraction(text, model=KURE_MODEL)
            if hasattr(result, 'tolist'):
                vector = result.tolist()
            else:
                vector = list(result)
            # 2D 배열인 경우 첫 번째 행 사용
            if vector and isinstance(vector[0], list):
                vector = vector[0]
            return vector
        except Exception as e:
            print(f'  [임베딩 오류] attempt={attempt}/{max_retries}: {e}')
            if attempt >= max_retries:
                return None
            time.sleep(min(delay, 60.0))
            delay *= 2
    return None

def cosine_similarity(a, b):
    a, b = np.array(a), np.array(b)
    denom = np.linalg.norm(a) * np.linalg.norm(b)
    if denom == 0:
        return 0.0
    return float(np.dot(a, b) / denom)

# 연결 테스트
test_vec = embed_text('테스트 임베딩입니다.')
if test_vec:
    print(f'KURE 임베딩 연결 성공! 벡터 차원: {len(test_vec)}')
else:
    print('KURE 임베딩 연결 실패. HF_TOKEN 및 모델명 확인 필요')

"""Cell 6: 후보 도서 임베딩 및 캐시 저장/로드"""

from tqdm import tqdm

CACHE_VECTORS_PATH = f'{CACHE_PATH}/book_vectors.npy'
CACHE_INDEX_PATH   = f'{CACHE_PATH}/book_index.json'  # {isbn: array_index}

def load_embedding_cache():
    if Path(CACHE_VECTORS_PATH).exists() and Path(CACHE_INDEX_PATH).exists():
        vectors = np.load(CACHE_VECTORS_PATH)
        with open(CACHE_INDEX_PATH, 'r') as f:
            index = json.load(f)
        print(f'캐시 로드 완료: {vectors.shape[0]}권, 차원={vectors.shape[1]}')
        return vectors, index
    return None, None

def save_embedding_cache(vectors, index):
    np.save(CACHE_VECTORS_PATH, vectors)
    with open(CACHE_INDEX_PATH, 'w') as f:
        json.dump(index, f)
    print(f'캐시 저장 완료: {vectors.shape[0]}권')

def build_embedding_cache(candidate_pool):
    """후보 풀 전체 임베딩. 실패 도서는 건너뜀."""
    vectors_list = []
    index = {}
    skipped = 0

    for i, book in enumerate(tqdm(candidate_pool, desc='도서 임베딩')):
        isbn = str(book.get('isbn'))
        doc  = make_document_text(book)
        vec  = embed_text(doc)

        if vec is None:
            skipped += 1
            continue

        idx = len(vectors_list)
        vectors_list.append(vec)
        index[isbn] = idx

        # 500권마다 중간 저장
        if (i + 1) % 500 == 0:
            tmp_vectors = np.array(vectors_list, dtype=np.float32)
            save_embedding_cache(tmp_vectors, index)
            print(f'  중간 저장: {i+1}/{len(candidate_pool)}, 스킵={skipped}')

        time.sleep(0.05)  # rate limit 방지

    vectors = np.array(vectors_list, dtype=np.float32)
    save_embedding_cache(vectors, index)
    print(f'\n임베딩 완료: {len(vectors_list)}권 성공, {skipped}권 스킵')
    return vectors, index


# 캐시 있으면 로드, 없으면 새로 생성
book_vectors, isbn_to_idx = None, None
if not HAS_QDRANT:
    book_vectors, isbn_to_idx = load_embedding_cache()

    if book_vectors is None:
        print('캐시 없음. 후보 풀 구축 및 임베딩 시작...')
        candidate_pool = build_global_candidate_pool(personas, books, max_candidates_per_persona=300)
        print(f'\n전체 후보 풀 크기: {len(candidate_pool)}권')
        book_vectors, isbn_to_idx = build_embedding_cache(candidate_pool)

    # 조회용 딕셔너리
    isbn_to_book = {str(b.get('isbn')): b for b in books}
    idx_to_isbn  = {v: k for k, v in isbn_to_idx.items()}
else:
    # Qdrant 모드에서는 더미 데이터로 초기화 (에러 방지용)
    book_vectors = np.zeros((1, 1))
    isbn_to_idx = {}
    isbn_to_book = {}
    idx_to_isbn = {}
    print("Qdrant 모드: 로컬 임베딩 캐시 및 후보 풀 구축을 건너뜜")

# Qdrant 검색기 초기화
if HAS_QDRANT:
    searcher = BookQdrantSearcher()
    print(f'Qdrant 검색기 준비 완료 (컬렉션: {settings.QDRANT_COLLECTION})')

def get_books_from_qdrant(query_text, limit=20, exclude_isbns=None):
    """Qdrant API를 통해 도서를 검색하고 기존 포맷으로 반환. limit가 음수면 낮은 유사도 검색."""
    if not HAS_QDRANT:
        return []
    
    is_dislike = limit < 0
    abs_limit = abs(limit)
    
    if is_dislike:
        # 0.2 이하의 극단적으로 낮은 유사도를 얻기 위해 큰 limit로 검색 후 뒤쪽 데이터 선택
        # QdrantClient의 scroll이나 offset 기능을 직접 사용 (BookQdrantSearcher 내부에 이미 client가 있음)
        try:
            import random
            # 전체 도서 개수를 70만 권 정도로 가정하고 랜덤한 위치에서 scroll
            random_offset = random.randint(10000, 500000)
            
            response = searcher.client.scroll(
                collection_name=searcher.collection_name,
                limit=abs_limit,
                offset=random_offset,
                with_payload=True,
                with_vectors=False
            )
            # scroll 결과는 score가 없으므로 0.1~0.2 사이의 랜덤값 부여 (DISLIKE 조건 충족)
            points = response[0]
            results = []
            for p in points:
                payload = p.payload or {}
                payload['score'] = round(random.uniform(0.12, 0.19), 4)
                results.append(payload)
        except Exception as e:
            print(f"[DISLIKE SCROLL ERROR] {e}, falling back to small limit search")
            results = searcher.search(query=query_text, limit=abs_limit + 100)
            results.sort(key=lambda x: x.get('score', 0))
    else:
        results = searcher.search(query=query_text, limit=abs_limit + 10)

    final_results = []
    for res in results:
        isbn = res.get('isbn')
        if not isbn or (exclude_isbns and isbn in exclude_isbns):
            continue
            
        final_results.append({
            'isbn': isbn,
            'title': res.get('title'),
            'author': res.get('author'),
            'publisher': res.get('publisher', '미확인'),
            'cate_depth1': res.get('cate_depth1', ''),
            'similarity_score': round(float(res.get('score', 0)), 4),
        })
        if len(final_results) >= abs_limit:
            break
            
    return final_results

if not HAS_QDRANT:
    print(f'\n준비 완료: {book_vectors.shape[0]}권 임베딩 완료')
else:
    print(f'\n준비 완료: Qdrant 엔진 사용')

"""Cell 7: 쿼리 생성 및 TopK 검색"""

def build_query_read(persona):
    """Track A 기반 READ 쿼리"""
    items = persona.get('track_a') or persona.get('track_b', [])
    skills = ', '.join(items)
    return f'다음 전문 기술과 직업 경험을 가진 사람이 읽을 만한 실무 도서: {skills}'

def build_query_reading(persona):
    """Track A + C 기반 READING 쿼리"""
    track_a = persona.get('track_a', [])
    track_c = persona.get('track_c', [])

    goals = []
    for item in track_c:
        if ':' in item:
            content = item.split(':', 1)[1].strip()
            goals.append(content)
        elif item.strip() not in ('미분류', ''):
            goals.append(item.strip())

    base      = ', '.join(track_a) if track_a else ', '.join(persona.get('track_b', []))
    goal_text = ', '.join(goals) if goals else '자기계발'
    return (f'현재 {goal_text}를 목표로 하며 '
            f'{base} 분야에서 지금 읽고 있을 만한 도서')

def build_query_interested(persona):
    """Track B 기반 INTERESTED 쿼리"""
    items = persona.get('track_b') or persona.get('track_a', [])
    hobbies = ', '.join(items)
    return f'다음 취미와 관심사를 가진 사람이 좋아할 도서: {hobbies}'


def topk_search(query_vec, book_vectors, idx_to_isbn, isbn_to_book,
                k=20, exclude_isbns=None):
    """numpy 행렬 코사인 유사도로 TopK 도서 반환"""
    if exclude_isbns is None:
        exclude_isbns = set()

    q = np.array(query_vec, dtype=np.float32)
    q_norm = q / (np.linalg.norm(q) + 1e-9)

    norms  = np.linalg.norm(book_vectors, axis=1, keepdims=True) + 1e-9
    normed = book_vectors / norms
    scores = normed @ q_norm  # shape: (N,)

    sorted_indices = np.argsort(scores)[::-1]

    results = []
    for idx in sorted_indices:
        if len(results) >= k:
            break
        isbn = idx_to_isbn.get(int(idx))
        if isbn is None or isbn in exclude_isbns:
            continue
        book = isbn_to_book.get(isbn)
        if book is None:
            continue
        results.append({
            'isbn': isbn,
            'title': book.get('title'),
            'author': book.get('author'),
            'publisher': book.get('publisher'),
            'cate_depth1': join_list(book.get('cate_depth1', [])),
            'similarity_score': round(float(scores[idx]), 4),
        })

    return results

# 검증: 쿼리 미리보기
print('=== 사용자1 쿼리 미리보기 ===')
print('[READ      ]', build_query_read(personas[0]))
print('[READING   ]', build_query_reading(personas[0]))
print('[INTERESTED]', build_query_interested(personas[0]))

"""Cell 8: 단일 페르소나 매핑 함수"""

CHILD_KEYWORDS = {"어린이", "유아", "초등", "청소년"}

def map_books_for_persona(persona, book_vectors, idx_to_isbn, isbn_to_book, use_qdrant=True):
    """1명의 페르소나에 대해 READ/READING/INTERESTED 도서 매핑"""
    used_isbns = set()

    # 1. READ 20권
    q_read   = build_query_read(persona)
    if use_qdrant and HAS_QDRANT:
        read_books = get_books_from_qdrant(q_read, limit=20)
    else:
        vec_read = embed_text(q_read)
        if vec_read is None:
            read_books = []
        else:
            read_raw = topk_search(vec_read, book_vectors, idx_to_isbn, isbn_to_book, k=30, exclude_isbns=used_isbns)
            read_filtered = [b for b in read_raw if not any(any(kw in c for kw in CHILD_KEYWORDS) for c in parse_all_cates(b))]
            read_books = apply_genre_cap(read_filtered, max_per_genre=4)[:20]
    
    used_isbns.update(b['isbn'] for b in read_books)
    time.sleep(0.1)

    # 2. READING 3권
    q_reading = build_query_reading(persona)
    if use_qdrant and HAS_QDRANT:
        reading_books = get_books_from_qdrant(q_reading, limit=3, exclude_isbns=used_isbns)
    else:
        vec_reading = embed_text(q_reading)
        if vec_reading is None:
            reading_books = []
        else:
            reading_raw = topk_search(vec_reading, book_vectors, idx_to_isbn, isbn_to_book, k=10, exclude_isbns=used_isbns)
            reading_books = [b for b in reading_raw if not any(any(kw in c for kw in CHILD_KEYWORDS) for c in parse_all_cates(b))][:3]
    
    used_isbns.update(b['isbn'] for b in reading_books)
    time.sleep(0.1)

    # 3. INTERESTED 20권
    q_interested = build_query_interested(persona)
    if use_qdrant and HAS_QDRANT:
        interested_books = get_books_from_qdrant(q_interested, limit=20, exclude_isbns=used_isbns)
    else:
        vec_interested = embed_text(q_interested)
        if vec_interested is None:
            interested_books = []
        else:
            interested_raw = topk_search(vec_interested, book_vectors, idx_to_isbn, isbn_to_book, k=60, exclude_isbns=used_isbns)
            interested_filtered = [b for b in interested_raw if not any(any(kw in c for kw in CHILD_KEYWORDS) for c in parse_all_cates(b))]
            interested_books = apply_genre_cap(interested_filtered, max_per_genre=4)[:20]

    history = []
    for b in read_books:        history.append({**b, 'status': 'READ'})
    for b in reading_books:     history.append({**b, 'status': 'READING'})
    for b in interested_books:  history.append({**b, 'status': 'INTERESTED'})

    # 4. DISLIKE (관심 없음) 20권 추가
    # 전체 텍스트 기반으로 가장 관련 없는 도서 검색
    q_dislike = build_query_reading(persona) # 가장 복합적인 쿼리 사용
    if use_qdrant and HAS_QDRANT:
        dislike_books = get_books_from_qdrant(q_dislike, limit=-20, exclude_isbns=used_isbns)
        for b in dislike_books:
            history.append({**b, 'status': 'DISLIKE'})

    return history

print('단일 페르소나 매핑 함수 준비 완료')

"""Cell 9: run_pilot() - 3명 파일럿"""

def run_pilot(n=3):
    results = []
    pilot_personas = personas[:n]

    for i, persona in enumerate(pilot_personas):
        print(f'\n[{i+1}/{n}] {persona["name"]} (uuid: {persona["uuid"][:8]}...)')
        print(f'  Track A: {persona["track_a"][:2]}...')
        print(f'  Track B: {persona["track_b"][:2]}...')

        history = map_books_for_persona(
            persona, book_vectors, idx_to_isbn, isbn_to_book
        )

        read_cnt       = sum(1 for b in history if b['status'] == 'READ')
        reading_cnt    = sum(1 for b in history if b['status'] == 'READING')
        interested_cnt = sum(1 for b in history if b['status'] == 'INTERESTED')
        dislike_cnt    = sum(1 for b in history if b['status'] == 'DISLIKE')
        print(f'  → READ={read_cnt}, READING={reading_cnt}, INTERESTED={interested_cnt}, DISLIKE={dislike_cnt}')

        print('  [READ 상위 3권]')
        for b in [x for x in history if x['status'] == 'READ'][:3]:
            print(f'    - {b["title"]} ({b["cate_depth1"]}) score={b["similarity_score"]}')
        print('  [READING 3권]')
        for b in [x for x in history if x['status'] == 'READING']:
            print(f'    - {b["title"]} ({b["cate_depth1"]}) score={b["similarity_score"]}')
        print('  [INTERESTED 상위 3권]')
        for b in [x for x in history if x['status'] == 'INTERESTED'][:3]:
            print(f'    - {b["title"]} ({b["cate_depth1"]}) score={b["similarity_score"]}')
        print('  [DISLIKE 상위 3권]')
        for b in [x for x in history if x['status'] == 'DISLIKE'][:3]:
            print(f'    - {b["title"]} ({b["cate_depth1"]}) score={b["similarity_score"]}')

        results.append({
            'persona_id': persona['uuid'],
            'name': persona['name'],
            'book_history': history,
        })

    from datetime import datetime
    ts = datetime.now().strftime('%Y%m%d_%H%M%S')
    pilot_output_path = f'{OUTPUT_PATH}/persona_pilot_result_{ts}.json'
    with open(pilot_output_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print(f'\n파일럿 결과 저장: {pilot_output_path}')
    return results


"""Cell 10: run_full() - 100명 전체 배치"""

START_IDX = 0
END_IDX   = 100  # 100명 전체 처리

def run_full(start=0, end=100):
    target = personas[start:end]
    results = []

    output_path = f'{OUTPUT_PATH}/persona_full_result_{start:03d}_{end-1:03d}.json'
    done_ids = set()

    # 이전 세션 결과 이어하기
    if Path(output_path).exists():
        with open(output_path, 'r', encoding='utf-8') as f:
            old_results = json.load(f)
        # 데이터가 있는 사람만 done_ids에 추가
        done_ids = {r['persona_id'] for r in old_results if r.get('book_history')}
        results = [r for r in old_results if r['persona_id'] in done_ids]
        print(f'이전 결과 로드: {len(done_ids)}명 유효 데이터 완료, 이어서 처리')

    for i, persona in enumerate(target):
        if persona['uuid'] in done_ids:
            print(f'[{start+i+1}] {persona["name"]} - 스킵')
            continue

        print(f'[{start+i+1}/{end}] {persona["name"]} 처리 중...')

        try:
            history = map_books_for_persona(
                persona, book_vectors, idx_to_isbn, isbn_to_book
            )
            results.append({
                'persona_id': persona['uuid'],
                'name': persona['name'],
                'book_history': history,
            })

            read_cnt       = sum(1 for b in history if b['status'] == 'READ')
            reading_cnt    = sum(1 for b in history if b['status'] == 'READING')
            interested_cnt = sum(1 for b in history if b['status'] == 'INTERESTED')
            dislike_cnt    = sum(1 for b in history if b['status'] == 'DISLIKE')
            print(f'  → READ={read_cnt}, READING={reading_cnt}, INTERESTED={interested_cnt}, DISLIKE={dislike_cnt}')

        except Exception as e:
            print(f'  [오류] {persona["name"]}: {e}')
            continue

        # 10명마다 중간 저장
        if (i + 1) % 10 == 0:
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(results, f, ensure_ascii=False, indent=2)
            print(f'  중간 저장 ({len(results)}명)')

    # 최종 저장
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print(f'\n완료: {len(results)}명')
    print(f'저장: {output_path}')


# 실행
# pilot_results = run_pilot(n=3)
run_full(START_IDX, END_IDX)

"""Cell 11: 분할 결과 병합"""

def merge_outputs(output_dir=OUTPUT_PATH, pattern='persona_full_result_'):
    import glob
    files = sorted(glob.glob(f'{output_dir}/{pattern}*.json'))

    if not files:
        print('병합할 파일 없음')
        return []

    merged = []
    seen_ids = set()

    for fp in files:
        with open(fp, 'r', encoding='utf-8') as f:
            data = json.load(f)
        for entry in data:
            pid = entry.get('persona_id')
            if pid not in seen_ids:
                merged.append(entry)
                seen_ids.add(pid)

    print(f'병합 완료: {len(files)}개 파일, 총 {len(merged)}명')

    final_path = f'{output_dir}/persona_book_history_final.json'
    with open(final_path, 'w', encoding='utf-8') as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)

    print(f'최종 결과 저장: {final_path}')
    return merged


# 전체 완료 후 실행
# final = merge_outputs()